name: openfold-env 
channels:
  - conda-forge
  - bioconda
  - nvidia
  - pytorch
dependencies:
  - python=3.11
  - libgcc
  - setuptools
  - pip
  - openmm==8.0.0
  - pdbfixer==1.9
  - biopython
  - numpy<2
  - pandas
  - PyYAML==5.4.1
  - requests
  - scipy
  - tqdm
  - typing-extensions==4.0
  - modelcif==0.7
  - awscli
  - ml-collections
  - aria2
  - mkl=2024.0
  - git
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - bioconda::mmseqs2
  - pip:
      - torch
      - torchvision
      - torchaudio
      - wandb
      - deepspeed
      - dm-tree==0.1.8
      - git+https://github.com/NVIDIA/dllogger.git
      - lightning
      - mpi4py
      - causal-conv1d>=1.4.0
      - mamba-ssm
      # - flash-attn
