name: openfold-env 
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pip
  - libgcc
  - setuptools
  - openmm
  - pdbfixer
  - pytorch-lightning
  - biopython
  - numpy
  - pandas
  - pyyaml
  - requests
  - scipy
  - tqdm
  - typing-extensions
  - wandb
  - modelcif
  - awscli
  - ml-collections
  - aria2
  - mkl
  - git
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2
  - bioconda::mmseqs2
  - pytorch::pytorch=2
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - pip:
      - deepspeed
      - dm-tree
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/Dao-AILab/flash-attention.git
